name: Node.js Publish UI CSS Packages

on:
  push:
    branches: [ 'master','console' ]
    paths:
      - 'health/micro-ui-react19/web/packages/css/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: cd health/micro-ui-react19/web/packages/css/ &&  yarn && yarn build && npm publish --tag console
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
